-- Please rename the database name before execution
ALTER DATABASE `MyDatabaseName` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- Convert each table to utf8mb4
ALTER TABLE `Addresses` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Attributs` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Blobs` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Booleans` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `ConfigService_parameters` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `ConfigService_xml` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Dates` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Elements` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `ElementStatistic` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Elements_Elements` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Elements_Groups` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Emails` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `EmailService` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `EmailServiceAttachementsToDelete` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Files` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `FileStatistic` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Floats` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `GlobalStatistic` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Groups` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Groups_Activities` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Groups_Groups` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Links` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `MultipleAttributs` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Numerics` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `SessionAdminService` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Strings` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Texts` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `TimeRanges` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Times` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Urls` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Users` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Users_Groups_Rights` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Users_Users` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `Varchars` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- rebuild the indexes (REPAIR is not available for InnoDB)
ALTER TABLE `Addresses` ENGINE = InnoDB;
ALTER TABLE `Attributs` ENGINE = InnoDB;
ALTER TABLE `Blobs` ENGINE = InnoDB;
ALTER TABLE `Booleans` ENGINE = InnoDB;
ALTER TABLE `ConfigService_parameters` ENGINE = InnoDB;
ALTER TABLE `ConfigService_xml` ENGINE = InnoDB;
ALTER TABLE `Dates` ENGINE = InnoDB;
ALTER TABLE `Elements` ENGINE = InnoDB;
ALTER TABLE `ElementStatistic` ENGINE = InnoDB;
ALTER TABLE `Elements_Elements` ENGINE = InnoDB;
ALTER TABLE `Elements_Groups` ENGINE = InnoDB;
ALTER TABLE `Emails` ENGINE = InnoDB;
ALTER TABLE `EmailService` ENGINE = InnoDB;
ALTER TABLE `EmailServiceAttachementsToDelete` ENGINE = InnoDB;
ALTER TABLE `Files` ENGINE = InnoDB;
ALTER TABLE `FileStatistic` ENGINE = InnoDB;
ALTER TABLE `Floats` ENGINE = InnoDB;
ALTER TABLE `GlobalStatistic` ENGINE = InnoDB;
ALTER TABLE `Groups` ENGINE = InnoDB;
ALTER TABLE `Groups_Activities` ENGINE = InnoDB;
ALTER TABLE `Groups_Groups` ENGINE = InnoDB;
ALTER TABLE `Links` ENGINE = InnoDB;
ALTER TABLE `MultipleAttributs` ENGINE = InnoDB;
ALTER TABLE `Numerics` ENGINE = InnoDB;
ALTER TABLE `SessionAdminService` ENGINE = InnoDB;
ALTER TABLE `Strings` ENGINE = InnoDB;
ALTER TABLE `Texts` ENGINE = InnoDB;
ALTER TABLE `TimeRanges` ENGINE = InnoDB;
ALTER TABLE `Times` ENGINE = InnoDB;
ALTER TABLE `Urls` ENGINE = InnoDB;
ALTER TABLE `Users` ENGINE = InnoDB;
ALTER TABLE `Users_Groups_Rights` ENGINE = InnoDB;
ALTER TABLE `Users_Users` ENGINE = InnoDB;
ALTER TABLE `Varchars` ENGINE = InnoDB;
